"""add telegram_connection model

Revision ID: 20260325_02
Revises: 20251123_01
Create Date: 2026-03-25

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260325_02'
down_revision = '20251123_01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.create_table(
        'telegram_connections',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('telegram_id', sa.String(), nullable=True),
        sa.Column('telegram_username', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('connected_at', sa.DateTime(), nullable=True),
        sa.Column('last_notification_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('telegram_id'),
    )
    op.create_index(op.f('ix_telegram_connections_id'), 'telegram_connections', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_connections_telegram_id'), 'telegram_connections', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_telegram_connections_user_id'), 'telegram_connections', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_index(op.f('ix_telegram_connections_user_id'), table_name='telegram_connections')
    op.drop_index(op.f('ix_telegram_connections_telegram_id'), table_name='telegram_connections')
    op.drop_index(op.f('ix_telegram_connections_id'), table_name='telegram_connections')
    op.drop_table('telegram_connections')
    # ### end Alembic commands ###
